### ISSUE TITLE
high resolution image?

### ISSUE THREAD

**Issue by BIGKnight** [DHZS/tf-deformable-conv-layer#1]
I have just read your code, and I have a question about it. in my perspective, the implementation of yours may not suit for the large resolution image inputs, because the internal implements need to construct a big pixels matrix for the calculation of defpthwise_conv2d operations.Have you test it in a high resolution dataset?
but I have to say your implementation is awesome and enlighten me a lot

**Comment by DHZS** [comment]
Hi @BIGKnight , I only tested the code on the MNIST dataset. I think the code is helpful for us to understand the methods in the paper more clearly, but it's not practical to use the code in real project, because this pure Python implementation is time consuming and needs a lot of cpu/gpu memory. 

You can improve efficiency by setting `num_deformable_group=1`. However, I think the best way to solve your problem is to use a C++ implementation like this: https://github.com/Zardinality/TF-deformable-conv

**Comment by BIGKnight** [comment]
yeah, that's what i`m doing now --- "use a C++ implementation",  anyway, thanks for your reply
