### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by tom-bu** [DHZS/tf-deformable-conv-layer#2]
I get this error when I build the model. Batch size is usually set to None, so I'm not sure why it expects a number here.
```
--> 110         batch_size = int(inputs.get_shape()[0])
    111         channel_in = int(inputs.get_shape()[-1])
    112         in_h, in_w = [int(i) for i in inputs.get_shape()[1: 3]]  # input feature map size

TypeError: __int__ returned non-int (type NoneType)
```

**Comment by DHZS** [comment]
Sorry, the code can only run in tf eager execution.

**Comment by tom-bu** [comment]
How difficult is it to make it available not in eager execution? I'd be willing to spend some time on this, but kind of need some guidance.

**Comment by tom-bu** [comment]
Are deformable convolutions still popularly used or are there better layers out there that perform similarly?

**Comment by DHZS** [comment]
I think it's not difficult to convert the code in graph execution. However, my re-implementation is not efficient, because I use high level TensorFlow API in my code. You can use c++ implementation in your project.
- TensorFlow: https://github.com/Zardinality/TF-deformable-conv
- PyTorch: https://github.com/chengdazhi/Deformable-Convolution-V2-PyTorch

Deformable conv is still useful in object detection, since it can adjust the receptive field and sample location dynamically according to the feature.
For more detail, you can refer to the following papers:
- [Deformable Convolutional Networks](https://arxiv.org/abs/1703.06211)
- [Deformable ConvNets v2: More Deformable, Better Results](https://arxiv.org/abs/1811.11168)

**Comment by madhav1ag** [comment]
@tom-bu Did you get success in converting it to non-eager executable code?
@DHZS can you help in this?
